// Minimal offline nutrition dataset (per 100g)
// Extend as needed; these values are illustrative only.
const OFFLINE_NUTRITION = [
	{ name: "Chicken breast", calories: 165, protein_g: 31, carbohydrates_total_g: 0, fat_total_g: 3.6 },
	{ name: "Salmon", calories: 208, protein_g: 20, carbohydrates_total_g: 0, fat_total_g: 13 },
	{ name: "Egg", calories: 155, protein_g: 13, carbohydrates_total_g: 1.1, fat_total_g: 11 },
	{ name: "Rice, white, cooked", calories: 130, protein_g: 2.7, carbohydrates_total_g: 28, fat_total_g: 0.3 },
	{ name: "Rice, brown, cooked", calories: 123, protein_g: 2.6, carbohydrates_total_g: 25.6, fat_total_g: 1 },
	{ name: "Potato, baked", calories: 93, protein_g: 2.5, carbohydrates_total_g: 21, fat_total_g: 0.1 },
	{ name: "Sweet potato", calories: 86, protein_g: 1.6, carbohydrates_total_g: 20, fat_total_g: 0.1 },
	{ name: "Broccoli", calories: 34, protein_g: 2.8, carbohydrates_total_g: 6.6, fat_total_g: 0.4 },
	{ name: "Spinach", calories: 23, protein_g: 2.9, carbohydrates_total_g: 3.6, fat_total_g: 0.4 },
	{ name: "Olive oil", calories: 884, protein_g: 0, carbohydrates_total_g: 0, fat_total_g: 100 },
	{ name: "Butter", calories: 717, protein_g: 0.9, carbohydrates_total_g: 0.1, fat_total_g: 81 },
	{ name: "Almonds", calories: 579, protein_g: 21.2, carbohydrates_total_g: 21.6, fat_total_g: 49.9 },
	{ name: "Peanut butter", calories: 588, protein_g: 25, carbohydrates_total_g: 20, fat_total_g: 50 },
	{ name: "Milk, whole", calories: 61, protein_g: 3.2, carbohydrates_total_g: 4.8, fat_total_g: 3.3 },
	{ name: "Yogurt, plain", calories: 59, protein_g: 10, carbohydrates_total_g: 3.6, fat_total_g: 0.4 },
	{ name: "Cheddar cheese", calories: 402, protein_g: 25, carbohydrates_total_g: 1.3, fat_total_g: 33 },
	{ name: "Apple", calories: 52, protein_g: 0.3, carbohydrates_total_g: 14, fat_total_g: 0.2 },
	{ name: "Banana", calories: 89, protein_g: 1.1, carbohydrates_total_g: 23, fat_total_g: 0.3 },
	{ name: "Orange", calories: 47, protein_g: 0.9, carbohydrates_total_g: 12, fat_total_g: 0.1 },
	{ name: "Blueberries", calories: 57, protein_g: 0.7, carbohydrates_total_g: 14.5, fat_total_g: 0.3 },
	{ name: "Strawberries", calories: 33, protein_g: 0.7, carbohydrates_total_g: 8, fat_total_g: 0.3 },
	{ name: "Avocado", calories: 160, protein_g: 2, carbohydrates_total_g: 8.5, fat_total_g: 14.7 },
	{ name: "Tomato", calories: 18, protein_g: 0.9, carbohydrates_total_g: 3.9, fat_total_g: 0.2 },
	{ name: "Onion", calories: 40, protein_g: 1.1, carbohydrates_total_g: 9.3, fat_total_g: 0.1 },
	{ name: "Garlic", calories: 149, protein_g: 6.4, carbohydrates_total_g: 33, fat_total_g: 0.5 },
	{ name: "Carrot", calories: 41, protein_g: 0.9, carbohydrates_total_g: 10, fat_total_g: 0.2 },
	{ name: "Lentils, cooked", calories: 116, protein_g: 9, carbohydrates_total_g: 20, fat_total_g: 0.4 },
	{ name: "Black beans, cooked", calories: 132, protein_g: 8.9, carbohydrates_total_g: 23.7, fat_total_g: 0.5 },
	{ name: "Chickpeas, cooked", calories: 164, protein_g: 8.9, carbohydrates_total_g: 27.4, fat_total_g: 2.6 },
	{ name: "Quinoa, cooked", calories: 120, protein_g: 4.1, carbohydrates_total_g: 21.3, fat_total_g: 1.9 },
	{ name: "Oats, dry", calories: 389, protein_g: 16.9, carbohydrates_total_g: 66.3, fat_total_g: 6.9 },
	{ name: "Bread, wheat", calories: 247, protein_g: 13, carbohydrates_total_g: 41, fat_total_g: 4.2 },
	{ name: "Pasta, cooked", calories: 131, protein_g: 5, carbohydrates_total_g: 25, fat_total_g: 1.1 },
	{ name: "Beef, ground 85% lean", calories: 250, protein_g: 26, carbohydrates_total_g: 0, fat_total_g: 17 },
	{ name: "Pork loin, roasted", calories: 242, protein_g: 27, carbohydrates_total_g: 0, fat_total_g: 14 },
	{ name: "Turkey breast", calories: 189, protein_g: 29, carbohydrates_total_g: 0, fat_total_g: 7 },
	{ name: "Tofu, firm", calories: 144, protein_g: 15.8, carbohydrates_total_g: 3.9, fat_total_g: 8 },
	{ name: "Shrimp, cooked", calories: 99, protein_g: 24, carbohydrates_total_g: 0.2, fat_total_g: 0.3 },
	{ name: "Tuna, canned in water", calories: 116, protein_g: 26, carbohydrates_total_g: 0, fat_total_g: 1 },
	{ name: "Tuna salad", calories: 187, protein_g: 12, carbohydrates_total_g: 6, fat_total_g: 12 },
	{ name: "Mayonnaise", calories: 680, protein_g: 0, carbohydrates_total_g: 0.6, fat_total_g: 75 },
	{ name: "Ketchup", calories: 112, protein_g: 1.3, carbohydrates_total_g: 26, fat_total_g: 0.2 },
	{ name: "Mustard", calories: 66, protein_g: 4.4, carbohydrates_total_g: 5.8, fat_total_g: 4 },
	{ name: "Honey", calories: 304, protein_g: 0.3, carbohydrates_total_g: 82, fat_total_g: 0 },
	{ name: "Sugar, white", calories: 387, protein_g: 0, carbohydrates_total_g: 100, fat_total_g: 0 },
	{ name: "Chocolate, dark", calories: 546, protein_g: 4.9, carbohydrates_total_g: 61, fat_total_g: 31 },
	{ name: "Ice cream, vanilla", calories: 207, protein_g: 3.5, carbohydrates_total_g: 24, fat_total_g: 11 },
	{ name: "Coffee, brewed", calories: 2, protein_g: 0.1, carbohydrates_total_g: 0, fat_total_g: 0 },
	{ name: "Tea, brewed", calories: 1, protein_g: 0, carbohydrates_total_g: 0.3, fat_total_g: 0 },
];

